
window.levels = [
  {
    audio: 'theme',
    level: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XOOROOOOXXOOROOOOOOOOOXKRX',
      'XXXOXXXOOOOXXXOXXOXOOOXOXX',
      'XOXMXOOOXXOOOOOOXOXXXOOOXX',
      'XOXXXOXXOOOXMXOOOOOOOOOXXX',
      'XOOOXOXXOXOOOOOXXXOXXXOOOX',
      'XXXOOOOXOXOXOXOXOOOOXOOXOX',
      'XOOXXOXMOXOXPXOXOMXOXOXXMX',
      'XMROOOOOOOOXXXOOOOOOXOOXOX',
      'XOOXXOOXXXOOOOOXOXOXXXOOOX',
      'XXXOOOOOOOOOMOXXOOOOOOOOXX',
      'XOOXXOXOXXXOOOOOOOXXXOXOOX',
      'XOOOXOXOOXOOOOXXXOXHXOXXOX',
      'XXOXXOXOOXOXOXMOXOOOOOXXOX',
      'DOROOOOOOOOXOXOOROOOOOOXMX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXX'
    ]
  },
  {
    audio: 'daft',
    level: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XKBOOOOOOOOOOOOOOOOOOOOOOX',
      'XXXOXXOXXCOXXXOMXXOXXOXXOX',
      'XCOOXOOOOOOOOOOOOOOOXBOXOX',
      'XXOXOOXOOXXXOHXXOOXOOXOXOX',
      'XMOOXOXOSXOOOOOXOOXOXOMXOX',
      'XOXOXOOXOXOXXXOXOXOOXOXXOX',
      'XOXOOXOXOXOXPXOXOXOXOOXVOD',
      'XOXXOXOOOOOOOXOOOOOXOOXXOX',
      'XOMXOOXOXOXXXOXOXOXOOOMXOX',
      'XOXXOOXOXOXXCXXOXOXOXXOXOX',
      'XOXOOOBOOOOOOOOOOOOOOXOXOX',
      'XOXOHXXXOXOOXOOXOXXXOOBOOX',
      'XOXXOOXOOXXXXXXXOOXOOXXXOX',
      'XCOOOOOOOVOOOOOOOOOOOOOOOX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXX'
    ]
  },
  {
    audio: 'theme',
    level: [
      'XXDXXXXXXXXXXXXXXXXXXXXXXX',
      'XBOOOOOOXMXOOOXMXOOOOOOOBX',
      'XOXOXOXOOOOOXOOOOOXOOXOXOX',
      'XOXOXOXOXXOOXOOXXOXXOXOXOX',
      'XOOOOOOOXOOXOXOOXOOOOOOOOX',
      'XXOXXOXXXOOOOOOOXXXOXXOXOX',
      'XMOXOOOOOOOXOXOOOOOOOXOOOX',
      'XOOXRXOXXXOXPXOXXXOXRXOOOX',
      'XXOXOOOOOOOXXXOOOOOOOXOXOX',
      'XXOXXOOXXOOOOOOOXXOOXXOXOX',
      'XXOOOOOOXOOXXXOOXOOOOOOXOX',
      'XOOXXXXOXXOXMXOXXOXXXXOXOX',
      'XOOOOOOOOOOXHXOOOOOOOOOOMX',
      'XXXOOOOXXOOOROOOXXOOOOXXXX',
      'XMOOXXOOOOXOXOXOOOMXXOOBKX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXX'
    ]
  },
  {
    audio: 'daft',
    level: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XXOOOOOOOOOOMMOOOOOOOOOOXX',
      'XMOXOOXOOXOOXXOOXOOXOOXOMX',
      'XXOXOXKBXOXOOOOXOXOOXOXOXX',
      'XOOOOXXXOOOOXXOOOOXXXOOOVX',
      'XOOXOOOOOXOOOOOOXOOOOOXOOX',
      'XOXOXOOOOOSXOOXOOOOOOXRXOX',
      'XOOOOOOXXXOXPOXOXXXOOOOOOD',
      'XOXXXOOCOOOXXXXOOBOOOXXXOX',
      'XOXMXOXOOXOOOOOOOXOOOXMXOX',
      'XOXOXOXXOOOXXXXOOXXOOXOXOX',
      'XOOOOOOXOOOOMMOOOOXOOOOOOX',
      'XOXXOXOOOXXOXXOXXOOOXOXXVX',
      'XOHXOXXXOOOOXXOOOOXOXOXHOX',
      'XMOOOOOOOXOOOOOOXOOOOOOOMX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXX'
    ]
  },
  {
    audio: 'daft',
    level: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XKBOOOOOOOOOOOOOOOOOOOOOOX',
      'XXXOXXOXXMOXXXOMXXOXXOXXOX',
      'XCOOXOOOOOOOOOOOOOOOXBOXOX',
      'XXOXOOXOOXXXOHXXOOXOOXOXOX',
      'XMOOXOXOSXOOOOOXOOXOXOMXOX',
      'XOXOXOOXOXOXXXOXOXOOXOXXOX',
      'XOXOOXOXOXOXPXOXOXOXOOXVOD',
      'XOXXOXOOOOOOOOOOOOOXOOXXOX',
      'XOMXOOXOXOXOXOXOXOXOOOMXOX',
      'XOXXOOXOXOXXCXXOXOXOXXOXOX',
      'XOXOOOBOOOOOOOOOOOOOOXOXOX',
      'XOXOHXXXOXOOXOOXOXXXOOBOOX',
      'XOXXOOXOOXXXXXXXOOXOOXXXOX',
      'XCOOOOOOOVOOOOOOOOOOOOOOOX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXX'
    ]
  },
  {
    audio: 'castle',
    level: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XMOOOOOOOOOOMOOOOOOOOOOOPX',
      'XOXXXXXXXXXXXXXXXXXXXXOOOX',
      'XOXOOOOOOOOOOOOOOOOROOOOOX',
      'XOXOXXXXXXXXXXXXXXXXXXXXOX',
      'XOXOXOOOOOOOVOOOOOOOOOOXOX',
      'XOXOXOXXXXXXXXXXXXXXXXOXOX',
      'XMXBXOXKOOVOGOVOOOOOOXCXMX',
      'XOXOXOXOOOOOVOOOODXOOXOXOX',
      'XOXOXOXXXXXXXXXXXXXHSXOXOX',
      'XOXOXHOOOOOOOOOOOOOOOXOXOX',
      'XOXOXXXXXXXXXXXXXXXXXXOXOX',
      'XOXHOOOOOOOOCOOOOOOOOOOXOX',
      'XOXXXXXXXXXXXXXXXXXXXXXXOX',
      'XMOOOOOOOOOOMOOOOOOOOOOOMX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXX'
    ]
  }
];
